[workspace]
resolver = "2"
members = [
    "crates/edp-core",
    "crates/edp-macos",
    "crates/edp-proto",
    "crates/usbcore",
    # "gui/src-tauri",  # M3 引入 Tauri GUI 时加入
]

[workspace.package]
version = "0.4.0"
edition = "2021"
rust-version = "1.75"
license = "Proprietary"
repository = "https://github.com/Evolution404/disk_client"

[workspace.dependencies]
# 内部 crate
edp-core = { path = "crates/edp-core" }
edp-macos = { path = "crates/edp-macos" }
edp-proto = { path = "crates/edp-proto" }

# 序列化
serde = { version = "1", features = ["derive"] }
serde_json = "1"
plist = "1"

# 加密（edp-core）
aes = "0.8"          # 仅用于 counter=0 交叉验证单测
md-5 = "0.10"
aes-gcm = "0.10"
rand = "0.8"

# 工具
clap = { version = "4", features = ["derive"] }
anyhow = "1"
thiserror = "1"
uuid = { version = "1", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
hex = "0.4"
rpassword = "7"

[profile.release]
lto = "thin"
strip = "symbols"
